Add taskverse plugin
jfrog/jfrog-cli-plugins-reg pull request #136
Opened 2023-01-23 23:02 UTC by elioengcomp

Add taskverse plugin

Requires https://github.com/jfrog/jfrog-cli-plugins/pull/99

2023-01-30 17:57 UTC, elioengcomp commented on plugins/taskverse.yml
> +repository: https://github.com/jfrog/jfrog-cli-plugins
I'm working on moving the source to its own repository.

2023-01-31 23:13 UTC, elioengcomp commented on plugins/taskverse.yml
> +repository: https://github.com/jfrog/jfrog-cli-plugins
Done.

2023-02-01 16:23 UTC, eyalbe4 requested changes
* Will you be to upgrade the version of the `jfrog-cli-core` and `jfrog-client-go` dependencies used by the plugin code to the latest available versions?
* It is also recommended to add a `RELEASE.md` file to the plugin codebase with the release notes, and reference it from the `README.md` file. See other plugins as a reference.
* In the "About this plugin" README section, I recommend replacing *Pipelines* with *JFrog Pipelines*, for more clarity about the product this plugin integrates with.
![image](https://user-images.githubusercontent.com/7830056/216101354-7d14d250-3c7d-44e8-af1e-b85c54f93036.png)

Once you make this change, we'll merge tis PR, and the tests will be autimatically triggered.

2023-02-01 21:08 UTC, elioengcomp commented
> * Will you be to upgrade the version of the `jfrog-cli-core` and `jfrog-client-go` dependencies used by the plugin code to the latest available versions?
> * It is also recommended to add a `RELEASE.md` file to the plugin codebase with the release notes, and reference it from the `README.md` file. See other plugins as a reference.
> * In the "About this plugin" README section, I recommend replacing _Pipelines_ with _JFrog Pipelines_, for more clarity about the product this plugin integrates with.
>   ![image](https://user-images.githubusercontent.com/7830056/216101354-7d14d250-3c7d-44e8-af1e-b85c54f93036.png)

Done.

2023-02-02 16:47 UTC, eyalbe4 requested changes
Will you be able to remove from this PR the README change? The PR should include only the plugin descriptor file (`plugins/taskverse.yml`) in this case.
The automatic tests that make sure the plugin is ready to be plublished will fail otherwise.
This is one of the guidelibes in the [JFrog CLI Plugin Developer Guide
](https://github.com/jfrog/jfrog-cli/blob/v2/guides/jfrog-cli-plugins-developer-guide.md)
![image](https://user-images.githubusercontent.com/7830056/216388064-2f4ac524-4736-4c6e-8ad6-bd8873d4d123.png)

2023-02-03 17:20 UTC, elioengcomp commented
> Will you be able to remove from this PR the README change? The PR should include only the plugin descriptor file (`plugins/taskverse.yml`) in this case. The automatic tests that make sure the plugin is ready to be plublished will fail otherwise. This is one of the guidelibes in the [JFrog CLI Plugin Developer Guide ](https://github.com/jfrog/jfrog-cli/blob/v2/guides/jfrog-cli-plugins-developer-guide.md) ![image](https://user-images.githubusercontent.com/7830056/216388064-2f4ac524-4736-4c6e-8ad6-bd8873d4d123.png) Once you make this change, we'll merge tis PR, and the tests will be autimatically triggered.

Done.

2023-02-03 18:22 UTC, merged

2023-02-07 08:50 UTC, eyalbe4 commented
Congrats @elioengcomp!
The **taskverse** plugin is released.
You can install it by running `jf plugin install taskverse`.

2023-02-07 19:08 UTC, elioengcomp commented
Awesome @eyalbe4!

I did try it and it is working like a charm.

Thank you for the guidance.