Change cli plugin release flow
jfrog/jfrog-cli-plugins-reg pull request #82
Opened 2021-12-12 11:18 UTC by gailazar300

Upload plugin's binaries and distribute to releases.jfrog.io.

2021-12-12 11:21 UTC, gailazar300 commented
I have read the Developer Terms and I hereby accept the terms

2021-12-12 13:06 UTC, RobiNino requested changes

2021-12-12 13:06 UTC, RobiNino commented on pipelinesScripts/pluginUpload.sh
> +  res=$(eval "./jfrog rt u ./$exeName $destPath")
The result of the command doesn't seems to be used, any reason to insert into this eval?

2021-12-12 13:06 UTC, RobiNino commented on pipelinesScripts/pluginUpload.sh
> +  res=$(eval "./jfrog rt cp \"$pluginPath/$JFROG_CLI_PLUGIN_VERSION/(*)\" \"$pluginPath/latest/{1}\" --flat")
Is this copy still needed if the plugin are being distributed to releases and downloaded from there?

If it is:
The result of the command doesn't seems to be used, any reason to insert into this eval?

2021-12-12 13:11 UTC, RobiNino requested changes

2021-12-12 13:11 UTC, RobiNino commented on pipelines.yml
> +            - GO111MODULE=on go get github.com/mikefarah/yq/v4
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

2021-12-24 04:47 UTC, eyalbe4 requested changes

2021-12-24 04:47 UTC, eyalbe4 commented on pipelines.yml
> +            # Download JFrog CLI
Download --> Install

2022-01-12 14:34 UTC, merged